kraken2 --db 16S_Greengenes_k2db --use-names --output Platz10.txt --report Platz10.report  --paired Platz10_R1.head.fastq Platz10_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz11.txt --report Platz11.report  --paired Platz11_R1.head.fastq Platz11_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz12.txt --report Platz12.report  --paired Platz12_R1.head.fastq Platz12_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz13.txt --report Platz13.report  --paired Platz13_R1.head.fastq Platz13_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz14.txt --report Platz14.report  --paired Platz14_R1.head.fastq Platz14_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz15.txt --report Platz15.report  --paired Platz15_R1.head.fastq Platz15_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz16.txt --report Platz16.report  --paired Platz16_R1.head.fastq Platz16_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz17.txt --report Platz17.report  --paired Platz17_R1.head.fastq Platz17_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz18.txt --report Platz18.report  --paired Platz18_R1.head.fastq Platz18_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz1.txt --report Platz1.report  --paired Platz1_R1.head.fastq Platz1_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz2.txt --report Platz2.report  --paired Platz2_R1.head.fastq Platz2_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz3.txt --report Platz3.report  --paired Platz3_R1.head.fastq Platz3_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz4.txt --report Platz4.report  --paired Platz4_R1.head.fastq Platz4_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz5.txt --report Platz5.report  --paired Platz5_R1.head.fastq Platz5_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz6.txt --report Platz6.report  --paired Platz6_R1.head.fastq Platz6_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz7.txt --report Platz7.report  --paired Platz7_R1.head.fastq Platz7_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz8.txt --report Platz8.report  --paired Platz8_R1.head.fastq Platz8_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output Platz9.txt --report Platz9.report  --paired Platz9_R1.head.fastq Platz9_R2.head.fastq
kraken2 --db 16S_Greengenes_k2db --use-names --output positivKo.txt --report positivKo.report  --paired positivKo_R1.head.fastq positivKo_R2.head.fastq
